templates:
  init: |-
    name: ${context.res.guresid}-emptydir
  manifests: |-
    emptydir.yaml:
      location: volumes
      data:
        name: {{ .init.name }}
        emptyDir:
          sizeLimit: 1024Mi