apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: test
entity:
  name: test
  type: volume
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |-
          name: ${context.res.guresid}-emptydir
        manifests: |-
          emptydir.yaml:
            location: volumes
            data:
              name: {{ .init.name }}
              emptyDir:
                sizeLimit: 1024Mi
