apiVersion: networking.gke.io/v1
kind: GCPGatewayPolicy
metadata:
  name: ${gateway_name}
  namespace: ${gateway_namespace}
spec:
  default:
    sslPolicy: ${gateway_name}
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: ${gateway_name}
    namespace: ${gateway_namespace}
