templates:
  init: |-
    name: ${context.app.id}-${context.env.id}
  manifests: |-
    namespace.yaml:
      location: cluster
      data:
        apiVersion: v1
        kind: Namespace
        metadata:
          labels:
            humanitec.io/app-id: ${context.app.id}
            humanitec.io/env-id: ${context.env.id}
            humanitec.io/env-type: ${context.env.type}
            pod-security.kubernetes.io/enforce: restricted
            mycompany.com/cost-center: ${resources['config#app'].outputs.cost_center}
          name: {{ .init.name }}
  outputs: |-
    namespace: {{ .init.name }}