apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: test
entity:
  name: test
  type: k8s-namespace
  driver_type: humanitec/template
  driver_inputs:
    values:
      templates:
        init: |-
          name: ${context.app.id}-${context.env.id}
        manifests: |-
          namespace.yaml:
            location: cluster
            data:
              apiVersion: v1
              kind: Namespace
              metadata:
                labels:
                  humanitec.io/app-id: ${context.app.id}
                  humanitec.io/env-id: ${context.env.id}
                  humanitec.io/env-type: ${context.env.type}
                  pod-security.kubernetes.io/enforce: restricted
                name: {{ .init.name }}
        outputs: |-
          namespace: {{ .init.name }}
