templates:
  manifests: |-
    quota.yaml:
      location: namespace
      data:
        apiVersion: v1
        kind: ResourceQuota
        metadata:
          name: compute-resources
        spec:
          hard:
            limits.cpu: $${resources['config#quota'].outputs.limits-cpu}
            limits.memory: $${resources['config#quota'].outputs.limits-memory}
    allow-nginx-ingress.yaml:
      location: namespace
      data:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: allow-nginx-ingress
        spec:
          podSelector: {}
          policyTypes:
          - Ingress
          ingress:
          - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: ingress-nginx
              podSelector:
                matchLabels:
                  app.kubernetes.io/name: ingress-nginx