templates:
  manifests: |-
    secret-store.yaml:
      location: namespace
      data:
        apiVersion: humanitec.io/v1alpha1
        kind: SecretStore
        metadata:
          name: ${context.app.id}-${context.env.id}
        spec:
          gcpsm:
            auth: {}
            projectID: ${resources['config#app'].outputs.gcp_project_id}
    network-policy.yaml:
      location: namespace
      data:
        apiVersion: networking.k8s.io/v1
        kind: NetworkPolicy
        metadata:
          name: default
        spec:
          podSelector: {}
          policyTypes:
            - Ingress
            - Egress
          ingress:
            - from:
              - podSelector: {}
          egress:
            - to:
              - podSelector: {}
            - to:
              - ipBlock:
                  cidr: 0.0.0.0/0
            - to:
                - namespaceSelector:
                    matchLabels:
                      kubernetes.io/metadata.name: kube-system
                  podSelector:
                    matchLabels:
                      k8s-app: kube-dns
              ports:
                - port: 53
                  protocol: UDP