apiVersion: entity.humanitec.io/v1b1
kind: Definition
metadata:
  id: test
entity:
  name: test
  type: k8s-service-account
  driver_type: humanitec/template
  driver_inputs:
    values:
      res_id: ${context.res.id}
      templates:
        init: |-
          name: {{ index ( .driver.values.res_id | splitList "." ) 1 }}
          principal: principal://iam.googleapis.com/projects/${resources['config.default#gke'].outputs.gke_project_number}/locations/global/workloadIdentityPools/${resources['config.default#gke'].outputs.gke_project_id}.svc.id.goog/subject/ns/${resources['k8s-namespace.default#k8s-namespace'].outputs.namespace}/sa/{{ index (splitList "." "${context.res.id}") 1 }}
        manifests: |-
          service-account.yaml:
            location: namespace
            data:
              apiVersion: v1
              kind: ServiceAccount
              metadata:
                labels:
                  humanitec.io/workload: {{ .init.name }}
                name: {{ .init.name }}
        outputs: |-
          name: {{ .init.name }}
          principal: {{ .init.principal }}
